name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #- uses: akhileshns/heroku-deploy@v3.2.6
      - name: Wait for Render Deployment
      - uses: bounceapp/render-action@0.2.0
        with:
          #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          #heroku_app_name: "wedding0424"
          #heroku_email: "hmlu36@gmail.com"
          #usedocker: false
          email: "hmlu36@gmail.com"
          password: ${{ secrets.RENDER_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cc61nsta49936rk9n5mg