name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
      - uses: bounceapp/render-action@0.2.0
        with:
          email: "hmlu36@gmail.com"
          password: ${{ secrets.RENDER_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cc61nsta49936rk9n5mg